// Code generated by wit-bindgen-go. DO NOT EDIT.

package query

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ResultSetShape is used for storage in variant or result types.
type ResultSetShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ResultSet{})]byte
}

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}
