// Code generated by wit-bindgen-go. DO NOT EDIT.

package query

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/query@0.1.0".
var Exports struct {
	// Execute represents the caller-defined, exported function "execute".
	//
	// Query execution
	//
	//	execute: func(conn-id: u32, query-text: string, params: list<sql-value>) -> result<result-set,
	//	error>
	Execute func(connID uint32, queryText string, params cm.List[SQLValue]) (result cm.Result[ResultSetShape, ResultSet, Error])

	// ExecuteBatch represents the caller-defined, exported function "execute-batch".
	//
	//	execute-batch: func(conn-id: u32, queries: list<string>) -> result<list<result-set>,
	//	error>
	ExecuteBatch func(connID uint32, queries cm.List[string]) (result cm.Result[ErrorShape, cm.List[ResultSet], Error])

	// Prepare represents the caller-defined, exported function "prepare".
	//
	// Prepared statements
	//
	//	prepare: func(conn-id: u32, query-text: string) -> result<u32, error>
	Prepare func(connID uint32, queryText string) (result cm.Result[ErrorShape, uint32, Error])

	// ExecutePrepared represents the caller-defined, exported function "execute-prepared".
	//
	//	execute-prepared: func(conn-id: u32, stmt-id: u32, params: list<sql-value>) ->
	//	result<result-set, error>
	ExecutePrepared func(connID uint32, stmtID uint32, params cm.List[SQLValue]) (result cm.Result[ResultSetShape, ResultSet, Error])

	// ClosePrepared represents the caller-defined, exported function "close-prepared".
	//
	//	close-prepared: func(conn-id: u32, stmt-id: u32) -> result<_, error>
	ClosePrepared func(connID uint32, stmtID uint32) (result cm.Result[Error, struct{}, Error])
}
