// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package query represents the exported interface "polyclient:sql/query@0.1.0".
//
// Query-related types and functions
package query

import (
	commontypes "github.com/polyclient/polyclient/bindings/polyclient/sql/common-types"
	"go.bytecodealliance.org/cm"
)

// SQLValue represents the type alias "polyclient:sql/query@0.1.0#sql-value".
//
// See [commontypes.SQLValue] for more information.
type SQLValue = commontypes.SQLValue

// Error represents the type alias "polyclient:sql/query@0.1.0#error".
//
// See [commontypes.Error] for more information.
type Error = commontypes.Error

// ColumnInfo represents the record "polyclient:sql/query@0.1.0#column-info".
//
//	record column-info {
//		name: string,
//		type-name: string,
//		is-primary-key: bool,
//		is-auto-increment: bool,
//		is-unique: bool,
//		is-nullable: bool,
//		default-value: option<sql-value>,
//		precision: option<u32>,
//		scale: option<f32>,
//		comment: option<string>,
//		length: option<u32>,
//		collation: option<string>,
//		ordinal-position: option<u32>,
//	}
type ColumnInfo struct {
	_               cm.HostLayout       `json:"-"`
	Name            string              `json:"name"`
	TypeName        string              `json:"type-name"`
	IsPrimaryKey    bool                `json:"is-primary-key"`
	IsAutoIncrement bool                `json:"is-auto-increment"`
	IsUnique        bool                `json:"is-unique"`
	IsNullable      bool                `json:"is-nullable"`
	DefaultValue    cm.Option[SQLValue] `json:"default-value"`
	Precision       cm.Option[uint32]   `json:"precision"`
	Scale           cm.Option[float32]  `json:"scale"`
	Comment         cm.Option[string]   `json:"comment"`
	Length          cm.Option[uint32]   `json:"length"`
	Collation       cm.Option[string]   `json:"collation"`
	OrdinalPosition cm.Option[uint32]   `json:"ordinal-position"`
}

// ResultMetadata represents the record "polyclient:sql/query@0.1.0#result-metadata".
//
//	record result-metadata {
//		columns: list<column-info>,
//		affected-rows: option<u64>,
//	}
type ResultMetadata struct {
	_            cm.HostLayout       `json:"-"`
	Columns      cm.List[ColumnInfo] `json:"columns"`
	AffectedRows cm.Option[uint64]   `json:"affected-rows"`
}

// Row represents the list "polyclient:sql/query@0.1.0#row".
//
//	type row = list<sql-value>
type Row cm.List[SQLValue]

// ResultSet represents the record "polyclient:sql/query@0.1.0#result-set".
//
//	record result-set {
//		metadata: result-metadata,
//		rows: list<row>,
//	}
type ResultSet struct {
	_        cm.HostLayout  `json:"-"`
	Metadata ResultMetadata `json:"metadata"`
	Rows     cm.List[Row]   `json:"rows"`
}
