// Code generated by wit-bindgen-go. DO NOT EDIT.

package query

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/query@0.1.0#execute
//export polyclient:sql/query@0.1.0#execute
func wasmexport_Execute(connId0 uint32, queryText0 *uint8, queryText1 uint32, params0 *SQLValue, params1 uint32) (result *cm.Result[ResultSetShape, ResultSet, Error]) {
	connID := (uint32)((uint32)(connId0))
	queryText := cm.LiftString[string]((*uint8)(queryText0), (uint32)(queryText1))
	params := cm.LiftList[cm.List[SQLValue]]((*SQLValue)(params0), (uint32)(params1))
	result_ := Exports.Execute(connID, queryText, params)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/query@0.1.0#execute-batch
//export polyclient:sql/query@0.1.0#execute-batch
func wasmexport_ExecuteBatch(connId0 uint32, queries0 *string, queries1 uint32) (result *cm.Result[ErrorShape, cm.List[ResultSet], Error]) {
	connID := (uint32)((uint32)(connId0))
	queries := cm.LiftList[cm.List[string]]((*string)(queries0), (uint32)(queries1))
	result_ := Exports.ExecuteBatch(connID, queries)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/query@0.1.0#prepare
//export polyclient:sql/query@0.1.0#prepare
func wasmexport_Prepare(connId0 uint32, queryText0 *uint8, queryText1 uint32) (result *cm.Result[ErrorShape, uint32, Error]) {
	connID := (uint32)((uint32)(connId0))
	queryText := cm.LiftString[string]((*uint8)(queryText0), (uint32)(queryText1))
	result_ := Exports.Prepare(connID, queryText)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/query@0.1.0#execute-prepared
//export polyclient:sql/query@0.1.0#execute-prepared
func wasmexport_ExecutePrepared(connId0 uint32, stmtId0 uint32, params0 *SQLValue, params1 uint32) (result *cm.Result[ResultSetShape, ResultSet, Error]) {
	connID := (uint32)((uint32)(connId0))
	stmtID := (uint32)((uint32)(stmtId0))
	params := cm.LiftList[cm.List[SQLValue]]((*SQLValue)(params0), (uint32)(params1))
	result_ := Exports.ExecutePrepared(connID, stmtID, params)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/query@0.1.0#close-prepared
//export polyclient:sql/query@0.1.0#close-prepared
func wasmexport_ClosePrepared(connId0 uint32, stmtId0 uint32) (result *cm.Result[Error, struct{}, Error]) {
	connID := (uint32)((uint32)(connId0))
	stmtID := (uint32)((uint32)(stmtId0))
	result_ := Exports.ClosePrepared(connID, stmtID)
	result = &result_
	return
}
