# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  collapse_walkthrough: true
  review_status: true
  poem: false
