# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: polyclient

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

nfpms:
  - maintainer: Juan Mesa <ju4n97@proton.me>
    description: A versatile database client with support for SQL and NoSQL.
    homepage: https://github.com/polyclient/polyclient
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk
      - archlinux

changelog:
  use: "github"
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999
