# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: polyclient
report_sizes: true

builds:
  - main: ./cmd/polyclient
    binary: polyclient
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/polyclient/polyclient/internal/version.version={{.Version}}
      - -X github.com/polyclient/polyclient/internal/version.branch={{.Branch}}
      - -X github.com/polyclient/polyclient/internal/version.shortCommit={{.ShortCommit}}
      - -X github.com/polyclient/polyclient/internal/version.fullCommit={{.FullCommit}}
      - -X github.com/polyclient/polyclient/internal/version.date={{.Date}}
      - -X github.com/polyclient/polyclient/internal/version.os={{.Os}}
      - -X github.com/polyclient/polyclient/internal/version.arch={{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  draft: true
  prerelease: auto

nfpms:
  - maintainer: Juan Mesa <ju4n97@proton.me>
    description: A versatile database client with support for SQL and NoSQL.
    homepage: https://github.com/polyclient/polyclient
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk

changelog:
  use: "github"
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^tmp:"
      - "^Merge branch"
      - "^Merge pull request"
      - "^Merge remote-tracking branch"
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other changes"
      order: 999
