# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: polyclient
report_sizes: true

builds:
  - main: ./cmd/polyclient
    binary: polyclient
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/polyclient/polyclient/internal/version.version={{.Version}}
      - -X github.com/polyclient/polyclient/internal/version.branch={{.Branch}}
      - -X github.com/polyclient/polyclient/internal/version.shortCommit={{.ShortCommit}}
      - -X github.com/polyclient/polyclient/internal/version.fullCommit={{.FullCommit}}
      - -X github.com/polyclient/polyclient/internal/version.date={{.Date}}
      - -X github.com/polyclient/polyclient/internal/version.os={{.Os}}
      - -X github.com/polyclient/polyclient/internal/version.arch={{.Arch}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64      
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
  algorithm: "sha256"

nfpms:
  - maintainer: Juan Mesa <ju4n97@proton.me>
    package_name: polyclient
    description: Unified database management platform.
    homepage: https://github.com/polyclient/polyclient
    license: GPL-3.0-or-later
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64      
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - apk
      - deb
      - rpm
      - archlinux

changelog:
  use: "github"
  format: "{{.SHA}}: {{.Message}} by @{{.AuthorUsername}}"
  sort: asc
  filters:
    exclude:
      - "^tmp:"
      - "^Merge branch"
      - "^Merge pull request"
      - "^Merge remote-tracking branch"
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Refactor"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Styling"
      regexp: '^.*?style(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: "Testing"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: "Other Changes"
      order: 999

release:
  draft: true
  prerelease: auto
