# yaml-language-server: $schema=https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json

assert_lefthook_installed: true

pre-commit:
  parallel: true

  jobs:
    - name: lint
      group:
        jobs:
          - run: task lint
            stage_fixed: true

    - name: format
      group:
        jobs:
          - run: task format
            stage_fixed: true

    - name: test
      group:
        jobs:
          - run: task test
