version = 1

[[annotations]]
path = ["go.mod", "go.sum", ".*", "*.md", "*.yaml", "*.toml", ".github/**/*"]
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-PolyClient-Plugin-Exception"

[[annotations]]
path = ["gui/**/*"]
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-PolyClient-Plugin-Exception"

[[annotations]]
path = [
    "plugins/**/manifest.json",
    "plugins/**/go.mod",
    "plugins/**/go.sum",
    "plugins/**/LICENSE.txt",
    "plugins/**/README.md",
]
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "schema/*"
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/*"
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "website/**/*"
SPDX-FileCopyrightText = "2025 The PolyClient Authors"
SPDX-License-Identifier = "CC-BY-4.0"
