version: "3"

vars:
  APP_NAME: polyclient

tasks:
  install:
    desc: Install the project dependencies and devtools
    cmds:
      - go mod tidy
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/evilmartians/lefthook@latest
      - task: init:workspace

  init:workspace:
    desc: Initialize Go workspace
    cmds:
      - ./scripts/init_workspace.sh

  dev:
    desc: Run the CLI in development mode for testing and debugging
    cmd: go run ./cmd/polyclient/main.go {{ .CLI_ARGS }}
    deps:
      - build:plugins

  build:
    desc: Build the CLI binary
    cmd: goreleaser build --snapshot --clean

  build:single-target:
    desc: Build the CLI binary
    cmd: goreleaser build --snapshot --clean --single-target

  build:plugins:
    desc: Build the plugins for Wasm target
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -o ./plugins/sqlite/sqlite-plugin.wasm ./plugins/sqlite/main.go
      - mkdir -p .polyclientdev/plugins/sqlite
      - cp ./plugins/sqlite/manifest.json ./plugins/sqlite/sqlite-plugin.wasm .polyclientdev/plugins/sqlite/
    deps:
      - generate:bindings

  generate:bindings:
    desc: Generate bindings for Wasm plugins
    cmds:
      - ./scripts/wit.sh

  release:
    desc: Create a new release (e.g., task release 0.1.0-beta.1)
    cmds:
      - ./scripts/release.sh {{ .CLI_ARGS }}

  lint:
    desc: Check code quality and identify potential issues
    cmd: golangci-lint run ./...

  lint:fix:
    desc: Check code quality and identify potential issues + fix them where possible
    cmd: golangci-lint run ./... --fix

  format:
    desc: Apply standard Go code formatting to all project files
    cmd: go fmt ./...

  test:
    desc: Run the project tests
    cmd: go test ./...
