// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package performance represents the exported interface "polyclient:sql/performance@0.1.0".
//
// Performance-related types and functions
package performance

import (
	commontypes "github.com/polyclient/polyclient/bindings/polyclient/sql/common-types"
)

// Error represents the type alias "polyclient:sql/performance@0.1.0#error".
//
// See [commontypes.Error] for more information.
type Error = commontypes.Error
