// Code generated by wit-bindgen-go. DO NOT EDIT.

package performance

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/performance@0.1.0".
var Exports struct {
	// GetPerformanceStatistics represents the caller-defined, exported function "get-performance-statistics".
	//
	// Performance operations
	//
	//	get-performance-statistics: func(conn-id: u32) -> result<list<tuple<string, string>>,
	//	error>
	GetPerformanceStatistics func(connID uint32) (result cm.Result[ErrorShape, cm.List[[2]string], Error])
}
