// Code generated by wit-bindgen-go. DO NOT EDIT.

package performance

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/performance@0.1.0#get-performance-statistics
//export polyclient:sql/performance@0.1.0#get-performance-statistics
func wasmexport_GetPerformanceStatistics(connId0 uint32) (result *cm.Result[ErrorShape, cm.List[[2]string], Error]) {
	connID := (uint32)((uint32)(connId0))
	result_ := Exports.GetPerformanceStatistics(connID)
	result = &result_
	return
}
