// Code generated by wit-bindgen-go. DO NOT EDIT.

package connection

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

func lift_OptionString(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[string]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[string])(cm.Some[string](cm.LiftString[string]((*uint8)(f1), (uint32)(f2))))
}

func lift_OptionU32(f0 uint32, f1 uint32) (v cm.Option[uint32]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[uint32])(cm.Some[uint32]((uint32)((uint32)(f1))))
}

func lift_ConnectionOptions(f0 *uint8, f1 uint32, f2 uint32, f3 *uint8, f4 uint32, f5 uint32, f6 *uint8, f7 uint32, f8 *[2]string, f9 uint32, f10 uint32, f11 uint32) (v ConnectionOptions) {
	v.URL = cm.LiftString[string](f0, f1)
	v.Username = lift_OptionString(f2, f3, f4)
	v.Password = lift_OptionString(f5, f6, f7)
	v.Parameters = cm.LiftList[cm.List[[2]string]](f8, f9)
	v.TimeoutMs = lift_OptionU32(f10, f11)
	return
}
