// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package connection represents the exported interface "polyclient:sql/connection@0.1.0".
//
// Connection-related types and functions
package connection

import (
	commontypes "github.com/polyclient/polyclient/bindings/polyclient/sql/common-types"
	"go.bytecodealliance.org/cm"
)

// SQLValue represents the type alias "polyclient:sql/connection@0.1.0#sql-value".
//
// See [commontypes.SQLValue] for more information.
type SQLValue = commontypes.SQLValue

// Error represents the type alias "polyclient:sql/connection@0.1.0#error".
//
// See [commontypes.Error] for more information.
type Error = commontypes.Error

// ConnectionOptions represents the record "polyclient:sql/connection@0.1.0#connection-options".
//
// Connection types
//
//	record connection-options {
//		url: string,
//		username: option<string>,
//		password: option<string>,
//		parameters: list<tuple<string, string>>,
//		timeout-ms: option<u32>,
//	}
type ConnectionOptions struct {
	_          cm.HostLayout      `json:"-"`
	URL        string             `json:"url"`
	Username   cm.Option[string]  `json:"username"`
	Password   cm.Option[string]  `json:"password"`
	Parameters cm.List[[2]string] `json:"parameters"`
	TimeoutMs  cm.Option[uint32]  `json:"timeout-ms"`
}
