// Code generated by wit-bindgen-go. DO NOT EDIT.

package connection

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/connection@0.1.0#connect
//export polyclient:sql/connection@0.1.0#connect
func wasmexport_Connect(options0 *uint8, options1 uint32, options2 uint32, options3 *uint8, options4 uint32, options5 uint32, options6 *uint8, options7 uint32, options8 *[2]string, options9 uint32, options10 uint32, options11 uint32) (result *cm.Result[ErrorShape, uint32, Error]) {
	options := lift_ConnectionOptions((*uint8)(options0), (uint32)(options1), (uint32)(options2), (*uint8)(options3), (uint32)(options4), (uint32)(options5), (*uint8)(options6), (uint32)(options7), (*[2]string)(options8), (uint32)(options9), (uint32)(options10), (uint32)(options11))
	result_ := Exports.Connect(options)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/connection@0.1.0#disconnect
//export polyclient:sql/connection@0.1.0#disconnect
func wasmexport_Disconnect(connId0 uint32) (result *cm.Result[Error, struct{}, Error]) {
	connID := (uint32)((uint32)(connId0))
	result_ := Exports.Disconnect(connID)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/connection@0.1.0#is-connected
//export polyclient:sql/connection@0.1.0#is-connected
func wasmexport_IsConnected(connId0 uint32) (result0 uint32) {
	connID := (uint32)((uint32)(connId0))
	result := Exports.IsConnected(connID)
	result0 = (uint32)(cm.BoolToU32(result))
	return
}
