// Code generated by wit-bindgen-go. DO NOT EDIT.

package connection

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/connection@0.1.0".
var Exports struct {
	// Connect represents the caller-defined, exported function "connect".
	//
	// Connection operations
	//
	//	connect: func(options: connection-options) -> result<u32, error>
	Connect func(options ConnectionOptions) (result cm.Result[ErrorShape, uint32, Error])

	// Disconnect represents the caller-defined, exported function "disconnect".
	//
	//	disconnect: func(conn-id: u32) -> result<_, error>
	Disconnect func(connID uint32) (result cm.Result[Error, struct{}, Error])

	// IsConnected represents the caller-defined, exported function "is-connected".
	//
	//	is-connected: func(conn-id: u32) -> bool
	IsConnected func(connID uint32) (result bool)
}
