blank_issues_enabled: true
contact_links:
  - name: PolyClient Feedback
    url: https://github.com/polyclient/polyclient/discussions/categories/ideas
    about: Share your suggestions and feedback.

  - name: PolyClient Questions
    url: https://github.com/polyclient/polyclient/discussions/categories/q-a
    about: Ask and answer PolyClient questions.
