// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package commontypes represents the exported interface "polyclient:sql/common-types@0.1.0".
//
// Common types shared across interfaces
package commontypes

import (
	"go.bytecodealliance.org/cm"
)

// SQLValue represents the variant "polyclient:sql/common-types@0.1.0#sql-value".
//
// Core SQL value types
//
//	variant sql-value {
//		null,
//		boolean(bool),
//		integer(s64),
//		float(f64),
//		text(string),
//		blob(list<u8>),
//		timestamp(u64),
//	}
type SQLValue cm.Variant[uint8, string, int64]

// SQLValueNull returns a [SQLValue] of case "null".
func SQLValueNull() SQLValue {
	var data struct{}
	return cm.New[SQLValue](0, data)
}

// Null returns true if [SQLValue] represents the variant case "null".
func (self *SQLValue) Null() bool {
	return self.Tag() == 0
}

// SQLValueBoolean returns a [SQLValue] of case "boolean".
func SQLValueBoolean(data bool) SQLValue {
	return cm.New[SQLValue](1, data)
}

// Boolean returns a non-nil *[bool] if [SQLValue] represents the variant case "boolean".
func (self *SQLValue) Boolean() *bool {
	return cm.Case[bool](self, 1)
}

// SQLValueInteger returns a [SQLValue] of case "integer".
func SQLValueInteger(data int64) SQLValue {
	return cm.New[SQLValue](2, data)
}

// Integer returns a non-nil *[int64] if [SQLValue] represents the variant case "integer".
func (self *SQLValue) Integer() *int64 {
	return cm.Case[int64](self, 2)
}

// SQLValueFloat returns a [SQLValue] of case "float".
func SQLValueFloat(data float64) SQLValue {
	return cm.New[SQLValue](3, data)
}

// Float returns a non-nil *[float64] if [SQLValue] represents the variant case "float".
func (self *SQLValue) Float() *float64 {
	return cm.Case[float64](self, 3)
}

// SQLValueText returns a [SQLValue] of case "text".
func SQLValueText(data string) SQLValue {
	return cm.New[SQLValue](4, data)
}

// Text returns a non-nil *[string] if [SQLValue] represents the variant case "text".
func (self *SQLValue) Text() *string {
	return cm.Case[string](self, 4)
}

// SQLValueBlob returns a [SQLValue] of case "blob".
func SQLValueBlob(data cm.List[uint8]) SQLValue {
	return cm.New[SQLValue](5, data)
}

// Blob returns a non-nil *[cm.List[uint8]] if [SQLValue] represents the variant case "blob".
func (self *SQLValue) Blob() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 5)
}

// SQLValueTimestamp returns a [SQLValue] of case "timestamp".
func SQLValueTimestamp(data uint64) SQLValue {
	return cm.New[SQLValue](6, data)
}

// Timestamp returns a non-nil *[uint64] if [SQLValue] represents the variant case "timestamp".
func (self *SQLValue) Timestamp() *uint64 {
	return cm.Case[uint64](self, 6)
}

var _SQLValueStrings = [7]string{
	"null",
	"boolean",
	"integer",
	"float",
	"text",
	"blob",
	"timestamp",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v SQLValue) String() string {
	return _SQLValueStrings[v.Tag()]
}

// ErrorKind represents the variant "polyclient:sql/common-types@0.1.0#error-kind".
//
// Error handling
//
//	variant error-kind {
//		connection-failed,
//		query-failed,
//		transaction-failed,
//		invalid-parameter,
//		timeout,
//		permission-denied,
//		not-supported,
//		other,
//	}
type ErrorKind uint8

const (
	ErrorKindConnectionFailed ErrorKind = iota
	ErrorKindQueryFailed
	ErrorKindTransactionFailed
	ErrorKindInvalidParameter
	ErrorKindTimeout
	ErrorKindPermissionDenied
	ErrorKindNotSupported
	ErrorKindOther
)

var _ErrorKindStrings = [8]string{
	"connection-failed",
	"query-failed",
	"transaction-failed",
	"invalid-parameter",
	"timeout",
	"permission-denied",
	"not-supported",
	"other",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e ErrorKind) String() string {
	return _ErrorKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e ErrorKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *ErrorKind) UnmarshalText(text []byte) error {
	return _ErrorKindUnmarshalCase(e, text)
}

var _ErrorKindUnmarshalCase = cm.CaseUnmarshaler[ErrorKind](_ErrorKindStrings[:])

// Error represents the record "polyclient:sql/common-types@0.1.0#error".
//
//	record error {
//		kind: error-kind,
//		message: string,
//		code: option<string>,
//	}
type Error struct {
	_       cm.HostLayout     `json:"-"`
	Kind    ErrorKind         `json:"kind"`
	Message string            `json:"message"`
	Code    cm.Option[string] `json:"code"`
}
