// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package metadata represents the exported interface "polyclient:sql/metadata@0.1.0".
//
// Metadata-related types and functions
package metadata

import (
	"github.com/polyclient/polyclient/bindings/polyclient/sql/transaction"
)

// IsolationLevel represents the type alias "polyclient:sql/metadata@0.1.0#isolation-level".
//
// See [transaction.IsolationLevel] for more information.
type IsolationLevel = transaction.IsolationLevel
