// Code generated by wit-bindgen-go. DO NOT EDIT.

package metadata

import (
	"github.com/polyclient/polyclient/bindings/polyclient/sql/transaction"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/metadata@0.1.0#supports-transactions
//export polyclient:sql/metadata@0.1.0#supports-transactions
func wasmexport_SupportsTransactions() (result0 uint32) {
	result := Exports.SupportsTransactions()
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport polyclient:sql/metadata@0.1.0#supports-prepared-statements
//export polyclient:sql/metadata@0.1.0#supports-prepared-statements
func wasmexport_SupportsPreparedStatements() (result0 uint32) {
	result := Exports.SupportsPreparedStatements()
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport polyclient:sql/metadata@0.1.0#supports-batch-operations
//export polyclient:sql/metadata@0.1.0#supports-batch-operations
func wasmexport_SupportsBatchOperations() (result0 uint32) {
	result := Exports.SupportsBatchOperations()
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport polyclient:sql/metadata@0.1.0#supports-isolation-level
//export polyclient:sql/metadata@0.1.0#supports-isolation-level
func wasmexport_SupportsIsolationLevel(level0 uint32) (result0 uint32) {
	level := (transaction.IsolationLevel)((uint32)(level0))
	result := Exports.SupportsIsolationLevel(level)
	result0 = (uint32)(cm.BoolToU32(result))
	return
}

//go:wasmexport polyclient:sql/metadata@0.1.0#get-capabilities
//export polyclient:sql/metadata@0.1.0#get-capabilities
func wasmexport_GetCapabilities() (result *cm.List[[2]string]) {
	result_ := Exports.GetCapabilities()
	result = &result_
	return
}
