// Code generated by wit-bindgen-go. DO NOT EDIT.

package metadata

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/metadata@0.1.0".
var Exports struct {
	// SupportsTransactions represents the caller-defined, exported function "supports-transactions".
	//
	// Feature support
	//
	//	supports-transactions: func() -> bool
	SupportsTransactions func() (result bool)

	// SupportsPreparedStatements represents the caller-defined, exported function "supports-prepared-statements".
	//
	//	supports-prepared-statements: func() -> bool
	SupportsPreparedStatements func() (result bool)

	// SupportsBatchOperations represents the caller-defined, exported function "supports-batch-operations".
	//
	//	supports-batch-operations: func() -> bool
	SupportsBatchOperations func() (result bool)

	// SupportsIsolationLevel represents the caller-defined, exported function "supports-isolation-level".
	//
	//	supports-isolation-level: func(level: isolation-level) -> bool
	SupportsIsolationLevel func(level IsolationLevel) (result bool)

	// GetCapabilities represents the caller-defined, exported function "get-capabilities".
	//
	// Database-specific capabilities
	//
	//	get-capabilities: func() -> list<tuple<string, string>>
	GetCapabilities func() (result cm.List[[2]string])
}
