// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package sqlplugin represents the world "polyclient:sql/sql-plugin@0.1.0".
//
// Export the world that SQL plugins must implement
package sqlplugin
