// Code generated by wit-bindgen-go. DO NOT EDIT.

package schema

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

func lift_OptionString(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[string]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[string])(cm.Some[string](cm.LiftString[string]((*uint8)(f1), (uint32)(f2))))
}
