// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package schema represents the exported interface "polyclient:sql/schema@0.1.0".
//
// Schema-related types and functions
package schema

import (
	commontypes "github.com/polyclient/polyclient/bindings/polyclient/sql/common-types"
	"github.com/polyclient/polyclient/bindings/polyclient/sql/query"
)

// Error represents the type alias "polyclient:sql/schema@0.1.0#error".
//
// See [commontypes.Error] for more information.
type Error = commontypes.Error

// ColumnInfo represents the type alias "polyclient:sql/schema@0.1.0#column-info".
//
// See [query.ColumnInfo] for more information.
type ColumnInfo = query.ColumnInfo
