// Code generated by wit-bindgen-go. DO NOT EDIT.

package schema

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/schema@0.1.0".
var Exports struct {
	// GetTables represents the caller-defined, exported function "get-tables".
	//
	// Schema operations
	//
	//	get-tables: func(conn-id: u32, schema-name: option<string>) -> result<list<string>,
	//	error>
	GetTables func(connID uint32, schemaName cm.Option[string]) (result cm.Result[ErrorShape, cm.List[string], Error])

	// GetColumns represents the caller-defined, exported function "get-columns".
	//
	//	get-columns: func(conn-id: u32, table: string, schema-name: option<string>) ->
	//	result<list<column-info>, error>
	GetColumns func(connID uint32, table string, schemaName cm.Option[string]) (result cm.Result[ErrorShape, cm.List[ColumnInfo], Error])
}
