// Code generated by wit-bindgen-go. DO NOT EDIT.

package schema

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/schema@0.1.0#get-tables
//export polyclient:sql/schema@0.1.0#get-tables
func wasmexport_GetTables(connId0 uint32, schemaName0 uint32, schemaName1 *uint8, schemaName2 uint32) (result *cm.Result[ErrorShape, cm.List[string], Error]) {
	connID := (uint32)((uint32)(connId0))
	schemaName := lift_OptionString((uint32)(schemaName0), (*uint8)(schemaName1), (uint32)(schemaName2))
	result_ := Exports.GetTables(connID, schemaName)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/schema@0.1.0#get-columns
//export polyclient:sql/schema@0.1.0#get-columns
func wasmexport_GetColumns(connId0 uint32, table0 *uint8, table1 uint32, schemaName0 uint32, schemaName1 *uint8, schemaName2 uint32) (result *cm.Result[ErrorShape, cm.List[ColumnInfo], Error]) {
	connID := (uint32)((uint32)(connId0))
	table := cm.LiftString[string]((*uint8)(table0), (uint32)(table1))
	schemaName := lift_OptionString((uint32)(schemaName0), (*uint8)(schemaName1), (uint32)(schemaName2))
	result_ := Exports.GetColumns(connID, table, schemaName)
	result = &result_
	return
}
