import { type IconSet, iconsNames } from '../types.ts';

export const polyclientDefault: IconSet = {
	[iconsNames.railHistory]: 'iconify:solar:history-outline',
	[iconsNames.railAssistant]: 'iconify:solar:face-scan-square-broken',
	[iconsNames.railPlugins]: 'iconify:solar:box-outline',
	[iconsNames.railNotifications]: 'iconify:solar:chat-unread-broken',
	[iconsNames.railSettings]: 'iconify:solar:settings-linear',

	[iconsNames.dbDatabase]: 'iconify:solar:database-linear',
	[iconsNames.dbSchema]: 'iconify:mdi:database',
	[iconsNames.dbTable]: 'iconify:mdi:database',
	[iconsNames.dbColumn]: 'iconify:mdi:database',
	[iconsNames.dbColumnPk]: 'iconify:mdi:database',
	[iconsNames.dbColumnFk]: 'iconify:mdi:database',
	[iconsNames.dbView]: 'iconify:mdi:database',
	[iconsNames.dbFunction]: 'iconify:mdi:database',
	[iconsNames.dbProcedure]: 'iconify:mdi:database',
	[iconsNames.dbTrigger]: 'iconify:mdi:database',
	[iconsNames.dbConnection]: 'iconify:mdi:database',
	[iconsNames.dbFolder]: 'iconify:mdi:database',

	[iconsNames.uiChevronLeft]: 'iconify:mdi:database',
	[iconsNames.uiChevronRight]: 'iconify:mdi:database',
	[iconsNames.uiChevronUp]: 'iconify:mdi:database',
	[iconsNames.uiChevronDown]: 'iconify:mdi:database',
	[iconsNames.uiArrowLeft]: 'iconify:mdi:database',
	[iconsNames.uiArrowRight]: 'iconify:mdi:database',
	[iconsNames.uiArrowUp]: 'iconify:mdi:database',
	[iconsNames.uiArrowDown]: 'iconify:mdi:database',
	[iconsNames.uiPrevious]: 'iconify:solar:arrow-left-outline',
	[iconsNames.uiNext]: 'iconify:solar:arrow-right-outline',
	[iconsNames.uiPlus]: 'iconify:mdi:database',
	[iconsNames.uiMinus]: 'iconify:mdi:database',
	[iconsNames.uiInfo]: 'iconify:mdi:database',
	[iconsNames.uiError]: 'iconify:mdi:database',
	[iconsNames.uiWarning]: 'iconify:mdi:database',
	[iconsNames.uiSuccess]: 'iconify:mdi:database',
};
