// Code generated by wit-bindgen-go. DO NOT EDIT.

package transaction

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

func lift_OptionIsolationLevel(f0 uint32, f1 uint32) (v cm.Option[IsolationLevel]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[IsolationLevel])(cm.Some[IsolationLevel]((IsolationLevel)((uint32)(f1))))
}
