// Code generated by wit-bindgen-go. DO NOT EDIT.

package transaction

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "polyclient:sql/transaction@0.1.0".
var Exports struct {
	// BeginTransaction represents the caller-defined, exported function "begin-transaction".
	//
	// Transaction operations
	//
	//	begin-transaction: func(conn-id: u32, isolation: option<isolation-level>) -> result<u32,
	//	error>
	BeginTransaction func(connID uint32, isolation cm.Option[IsolationLevel]) (result cm.Result[ErrorShape, uint32, Error])

	// CommitTransaction represents the caller-defined, exported function "commit-transaction".
	//
	//	commit-transaction: func(conn-id: u32, transaction-id: u32) -> result<_, error>
	CommitTransaction func(connID uint32, transactionID uint32) (result cm.Result[Error, struct{}, Error])

	// RollbackTransaction represents the caller-defined, exported function "rollback-transaction".
	//
	//	rollback-transaction: func(conn-id: u32, transaction-id: u32) -> result<_, error>
	RollbackTransaction func(connID uint32, transactionID uint32) (result cm.Result[Error, struct{}, Error])
}
