// Code generated by wit-bindgen-go. DO NOT EDIT.

package transaction

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "polyclient:sql@0.1.0".

//go:wasmexport polyclient:sql/transaction@0.1.0#begin-transaction
//export polyclient:sql/transaction@0.1.0#begin-transaction
func wasmexport_BeginTransaction(connId0 uint32, isolation0 uint32, isolation1 uint32) (result *cm.Result[ErrorShape, uint32, Error]) {
	connID := (uint32)((uint32)(connId0))
	isolation := lift_OptionIsolationLevel((uint32)(isolation0), (uint32)(isolation1))
	result_ := Exports.BeginTransaction(connID, isolation)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/transaction@0.1.0#commit-transaction
//export polyclient:sql/transaction@0.1.0#commit-transaction
func wasmexport_CommitTransaction(connId0 uint32, transactionId0 uint32) (result *cm.Result[Error, struct{}, Error]) {
	connID := (uint32)((uint32)(connId0))
	transactionID := (uint32)((uint32)(transactionId0))
	result_ := Exports.CommitTransaction(connID, transactionID)
	result = &result_
	return
}

//go:wasmexport polyclient:sql/transaction@0.1.0#rollback-transaction
//export polyclient:sql/transaction@0.1.0#rollback-transaction
func wasmexport_RollbackTransaction(connId0 uint32, transactionId0 uint32) (result *cm.Result[Error, struct{}, Error]) {
	connID := (uint32)((uint32)(connId0))
	transactionID := (uint32)((uint32)(transactionId0))
	result_ := Exports.RollbackTransaction(connID, transactionID)
	result = &result_
	return
}
