// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package transaction represents the exported interface "polyclient:sql/transaction@0.1.0".
//
// Transaction-related types and functions
package transaction

import (
	commontypes "github.com/polyclient/polyclient/bindings/polyclient/sql/common-types"
	"go.bytecodealliance.org/cm"
)

// Error represents the type alias "polyclient:sql/transaction@0.1.0#error".
//
// See [commontypes.Error] for more information.
type Error = commontypes.Error

// IsolationLevel represents the enum "polyclient:sql/transaction@0.1.0#isolation-level".
//
// Transaction types
//
//	enum isolation-level {
//		read-uncommitted,
//		read-committed,
//		repeatable-read,
//		serializable
//	}
type IsolationLevel uint8

const (
	IsolationLevelReadUncommitted IsolationLevel = iota
	IsolationLevelReadCommitted
	IsolationLevelRepeatableRead
	IsolationLevelSerializable
)

var _IsolationLevelStrings = [4]string{
	"read-uncommitted",
	"read-committed",
	"repeatable-read",
	"serializable",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e IsolationLevel) String() string {
	return _IsolationLevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e IsolationLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *IsolationLevel) UnmarshalText(text []byte) error {
	return _IsolationLevelUnmarshalCase(e, text)
}

var _IsolationLevelUnmarshalCase = cm.CaseUnmarshaler[IsolationLevel](_IsolationLevelStrings[:])
