[book]
title = "PolyClient Documentation"
authors = ["Juan Mesa"]
language = "en"
multilingual = false
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
smart-punctuation = true
additional-js = [
    "preprocessors/mermaid.min.js",
    "preprocessors/mermaid-init.js",
]
git-repository-url = "https://github.com/polyclient/polyclient"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/polyclient/polyclient/edit/master/{path}"
